apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: iamrishupatel/query
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: query-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 8003
      targetPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: query-nodeport-srv
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - name: query
      port: 8003
      targetPort: 8003
      protocol: TCP
